#!usr/bin/env python
# -*- coding: UTF-8 -*-

a = 0
for i in range (1,5):
	for j in range (1,5):
		for k in range (1,5):
			if ( i != j ) and ( j != k) and (i != k):
				print i,j,k
				a = a + 1
print a
